Category.create(name: "Europe")
Category.create(name: "Asia")

Category.create(name: "Europe")
Category.create(name: "Asia")
Category.create(name: "Europe")
Category.create(name: "Asia")
Category.create(name: "Europe")
Category.create(name: "Asia")
Category.create(name: "Europe")
Category.create(name: "Asia")
Category.create(name: "Europe")
Category.create(name: "Asia")
